### ISSUE TITLE
Template tests fail on Fedora due to Windows-style pathnames

### ISSUE THREAD

**Issue by GeeWee** [Dotnet-Boxed/Templates#802]
### Describe the bug

When running the tests (either via Cake or via dotnet test) on my local Fedora machine, some tests do not pass. I have a sneaking suspicion that is is because of of some windows-style paths in some of the tests.

### To Reproduce
I can reproduce it by doing the following:
- Fork the repo
- `cd {projectDir}/Tests/Boxed.Templates.FunctionalTest`
- `dotnet test --filter ApiTemplateTest.RestoreBuildTestRun_HttpsEverywhereFalse_SuccessfulAsync`
And the test will fail. This is not the only one that fails, it is simply an example of one that does.

I get the following output. I have highlighted what I think is the important part after the humongous log message.
```
Test run for /home/geewee/programming/dotnet-boxed/Tests/Boxed.Templates.FunctionalTest/bin/Debug/netcoreapp3.1/Boxed.Templates.FunctionalTest.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0-release-20200703-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: /home/geewee/programming/dotnet-boxed/Tests/Boxed.Templates.FunctionalTest/log.txt

A total of 1 test files matched the specified pattern.
[xUnit.net 00:01:10.37]     Boxed.Templates.FunctionalTest.ApiTemplateTest.RestoreBuildTestRun_HttpsEverywhereFalse_SuccessfulAsync [FAIL]
  X Boxed.Templates.FunctionalTest.ApiTemplateTest.RestoreBuildTestRun_HttpsEverywhereFalse_SuccessfulAsync [1m 9s]
  Error Message:
   Boxed.DotnetNewTest.ProcessStartException : Process start failed. Filename:<dotnet> Arguments:<run --no-restore --urls http://localhost:41047/;https://localhost:43167/> WorkingDirectory:</tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source\ApiHttpsEverywhereFalse>.
---- System.ComponentModel.Win32Exception : No such file or directory
  Stack Trace:
     at Boxed.DotnetNewTest.ProcessExtensions.StartProcessAsync(String filename, String arguments, String workingDirectory, TextWriter outputTextWriter, TextWriter errorTextWriter, Boolean showShellWindow, CancellationToken cancellationToken)
   at Boxed.DotnetNewTest.ProcessExtensions.StartAsync(String workingDirectory, String fileName, String arguments, Boolean showShellWindow, CancellationToken cancellationToken)
   at Boxed.DotnetNewTest.ProjectExtensions.AssertStartAsync(String workingDirectory, String fileName, String arguments, Boolean showShellWindow, CancellationToken cancellationToken)
   at Boxed.DotnetNewTest.ProjectExtensions.<DotnetRunInternalAsync>g__Dispose|8_2(CancellationTokenSource cancellationTokenSource, Task task, Boolean showShellWindow)
   at Boxed.DotnetNewTest.ProjectExtensions.DotnetRunInternalAsync(Func`3 readinessCheck, HttpClient httpClient, HttpClient httpsClient, String directoryPath, Nullable`1 noRestore, Nullable`1 timeout, Boolean showShellWindow, Uri[] urls)
   at Boxed.DotnetNewTest.ProjectExtensions.DotnetRunAsync(Project project, String projectRelativeDirectoryPath, Func`3 readinessCheck, Func`3 action, Nullable`1 noRestore, Func`5 validateCertificate, Nullable`1 timeout, Boolean showShellWindow)
   at Boxed.Templates.FunctionalTest.ApiTemplateTest.RestoreBuildTestRun_HttpsEverywhereFalse_SuccessfulAsync() in /home/geewee/programming/dotnet-boxed/Tests/Boxed.Templates.FunctionalTest/ApiTemplateTest.cs:line 219
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Boxed.DotnetNewTest.ProcessExtensions.StartProcessAsync(String filename, String arguments, String workingDirectory, TextWriter outputTextWriter, TextWriter errorTextWriter, Boolean showShellWindow, CancellationToken cancellationToken)
  Standard Output Messages:
 Executing dotnet new --install "/home/geewee/programming/dotnet-boxed/Source/ApiTemplate" from /home/geewee/programming/dotnet-boxed/Tests/Boxed.Templates.FunctionalTest/bin/Debug/netcoreapp3.1
 
 Result: 
 Succeeded
 
 
 
 Output: Usage: new [options]
 
 Options:
   -h, --help          Displays help for this command.
   -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
   -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
   -o, --output        Location to place the generated output.
   -i, --install       Installs a source or a template pack.
   -u, --uninstall     Uninstalls a source or a template pack.
   --nuget-source      Specifies a NuGet source to use during install.
   --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
   --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
   --force             Forces content to be generated even if it would change existing files.
   -lang, --language   Filters templates based on language and specifies the language of the template to create.
   --update-check      Check the currently installed template packs for updates.
   --update-apply      Check the currently installed template packs for update, and install the updates.
 
 
 Templates                       Short Name         Language      Tags                                 
 ------------------------------------------------------------------------------------------------------
 .editorconfig file              editorconfig       [C#]          Config                               
 .gitattributes file             gitattributes      [C#]          Config                               
 NuGet Package Boxed             nuget              [C#]          NuGet/Package/Library/Boxed          
 ASP.NET Core API Boxed          api                [C#]          Web/WebAPI/Boxed/API/Swagger/Open API
 ASP.NET Core GraphQL Boxed      graphql            [C#]          Web/WebAPI/Boxed/GraphQL/API         
 ASP.NET Core Orleans Boxed      orleans            [C#]          Web/WebAPI/Boxed/Orleans/API/Actor   
 
 Examples:
     dotnet new nuget
     dotnet new graphql
     dotnet new --help
 
 
 Executing dotnet new api --name "ApiHttpsEverywhereFalse" --https-everywhere "false" from /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5
 
 Result: 
 Succeeded
 
 
 
 Output: The template "ASP.NET Core API Boxed" was created successfully.
 
 Processing post-creation actions...
 Running 'dotnet restore' on ApiHttpsEverywhereFalse/ApiHttpsEverywhereFalse.sln...
   Determining projects to restore...
   Restored /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest/ApiHttpsEverywhereFalse.IntegrationTest.csproj (in 394 ms).
   Restored /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse/ApiHttpsEverywhereFalse.csproj (in 394 ms).
 
 Restore succeeded.
 
 Description: Open the to-do list for the project in a web browser.
 Manual instructions: Open the TODO.html in a web browser to see a to-do list.
 
 
 
 Executing dotnet restore from /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse
 
 Result: 
 Succeeded
 
 
 
 Output:   Determining projects to restore...
   All projects are up-to-date for restore.
 
 
 Executing dotnet build --no-restore from /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse
 
 Result: 
 Succeeded
 
 
 
 Output: Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
 Copyright (C) Microsoft Corporation. All rights reserved.
 
 MinVer : warning MINVER1001: '/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse' is not a valid working directory. Using default version 0.0.0-preview.0. [/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse/ApiHttpsEverywhereFalse.csproj]
   MinVer: Calculated version 0.0.0-preview.0.
   ApiHttpsEverywhereFalse -> /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse/bin/Debug/netcoreapp3.1/ApiHttpsEverywhereFalse.dll
 MinVer : warning MINVER1001: '/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest' is not a valid working directory. Using default version 0.0.0-preview.0. [/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest/ApiHttpsEverywhereFalse.IntegrationTest.csproj]
   MinVer: Calculated version 0.0.0-preview.0.
   ApiHttpsEverywhereFalse.IntegrationTest -> /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest/bin/Debug/netcoreapp3.1/ApiHttpsEverywhereFalse.IntegrationTest.dll
 
 Build succeeded.
 
 MinVer : warning MINVER1001: '/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse' is not a valid working directory. Using default version 0.0.0-preview.0. [/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse/ApiHttpsEverywhereFalse.csproj]
 MinVer : warning MINVER1001: '/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest' is not a valid working directory. Using default version 0.0.0-preview.0. [/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest/ApiHttpsEverywhereFalse.IntegrationTest.csproj]
     2 Warning(s)
     0 Error(s)
 
 Time Elapsed 00:00:01.92
 
 
 Executing dotnet test --no-restore from /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse
 
 Result: 
 Succeeded
 
 
 
 Output: MinVer : warning MINVER1001: '/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse' is not a valid working directory. Using default version 0.0.0-preview.0. [/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source/ApiHttpsEverywhereFalse/ApiHttpsEverywhereFalse.csproj]
 MinVer : warning MINVER1001: '/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest' is not a valid working directory. Using default version 0.0.0-preview.0. [/tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest/ApiHttpsEverywhereFalse.IntegrationTest.csproj]
 Test run for /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Tests/ApiHttpsEverywhereFalse.IntegrationTest/bin/Debug/netcoreapp3.1/ApiHttpsEverywhereFalse.IntegrationTest.dll(.NETCoreApp,Version=v3.1)
 Microsoft (R) Test Execution Command Line Tool Version 16.7.0
 Copyright (c) Microsoft Corporation.  All rights reserved.
 
 Starting test execution, please wait...
 
 A total of 1 test files matched the specified pattern.
 
 Test Run Successful.
 Total tests: 28
      Passed: 28
  Total time: 2.1741 Seconds
 
 
 Executing dotnet run --no-restore --urls http://localhost:41047/;https://localhost:43167/ from /tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source\ApiHttpsEverywhereFalse
 
 Waiting for app to start and pass readiness check.
 
 Waiting for app to start. Readiness check threw exception...
 
 Waiting for app to start. Readiness check threw exception...

... a billion of these

Timed out after waiting 00:01:00 for app to start using dotnet run.
```

What jumped out at me as important here was the error message - particularly the working directory:
`Boxed.DotnetNewTest.ProcessStartException : Process start failed. Filename:<dotnet> Arguments:<run --no-restore --urls http://localhost:41047/;https://localhost:43167/> WorkingDirectory:</tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source\ApiHttpsEverywhereFalse>.`
The working directory part:
`WorkingDirectory:</tmp/511b0c68e52a4e5ba9cdd24b6493e1a5/ApiHttpsEverywhereFalse/Source\ApiHttpsEverywhereFalse>.` - the backward slash is a windows-style path separator which doesn't work on Unix systems. To test my theory I tried replacing the windows style path.

I changed the code at `ApiTemplateTest:221` from 
`
@"Source\ApiHttpsEverywhereFalse",
`
to `Path.Join("Source", "ApiHttpsEverywhereFalse")`
And when I do that **the test passes fine**

## The real mystery - why does CI pass?
At first I figured this was simply a question of the project being built on a Windows machine, without anyone having tested it on Linux. I would submit a PR to fix the paths and that would be it.
However, I can see that the project builds on Ubuntu just fine in the CI.
This is where I'm stumped. To my knowledge Ubuntu and Fedora doesn't treat paths any different, so why does it work on CI and not locally? Am I missing something?

## Environment
Resharper 2020.2 and  `dotnet --version` outputs `3.1.402`
Which version of Visual Studio and the dotnet SDK were you using?

**Comment by RehanSaeed** [comment]
Want to submit that as a PR?

Not sure why CI would still work. I've noticed that some Unix programs are resistant to Windows path separators and continue to work.

**Comment by GeeWee** [comment]
Yeah I can absolutely submit it as a PR - I was just worried that because it was passing on CI the problem was something else I was missing.

**Comment by GeeWee** [comment]
PR submitted, still having some issues where the tests fail intermittently due to timing out.
I'm on a reasonably beefy computer so I'm a little puzzled as to why this happens. Will keep investigating.

**Comment by RehanSaeed** [comment]
Your PR is a good one. Now merged. Thanks for the fix.

Occasionally, I see the MacOS build fail on GitHub Actions. I've increased the timeout but it's not that. The functional tests spawn new processes, so there may be some issue with that that I'm not aware of. I think the next step should be to pass `--verbosity=Diagnostic` to get more info when running the tests.

**Comment by GeeWee** [comment]
Hm, that's interesting. Processes are messy. Speaking of timeouts, is there a reason that we limit the tests to run in sequence and with one thread at a time?

**Comment by RehanSaeed** [comment]
The `dotnet new` command is not happy when you run multiple commands against it at the same time. You get all kinds of odd errors, although things are a lot better in the latest .NET SDK. It may now be possible to run the `dotnet new --install` command once at the beginning of a test run and then run all other commands `dotnet new api`, `dotnet build` etc. subsequently. The CLI is not built with running concurrent tests like this in mind though, so you get weird behaviour.

**Comment by RehanSaeed** [comment]
Looking at the latest failure, I think Orleans has trouble on MacOS. E.g.

https://github.com/Dotnet-Boxed/Templates/runs/1205333399?check_suite_focus=true
